import { ReactNode } from "react";
import { Metadata } from "next";
import { MantineProvider, ColorSchemeScript } from "@mantine/core";

import { theme } from "@/theme";

import "@mantine/core/styles.css";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
    <head>
      <ColorSchemeScript forceColorScheme="light" />
    </head>
    <body>
    <MantineProvider theme={theme}>{children}</MantineProvider>
    </body>
    </html>
  );
}
