name: api-build

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - "api/**"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DigitalOcean Container Registry
        uses: docker/login-action@v3
        with:
          registry: registry.digitalocean.com/swiftbooks
          username: ${{ secrets.DO_REGISTRY_TOKEN }}
          password: ${{ secrets.DO_REGISTRY_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: api.Dockerfile
          push: true
          tags: registry.digitalocean.com/swiftbooks/api:latest
          cache-from: type=registry,ref=registry.digitalocean.com/swiftbooks/api:latest
          cache-to: type=inline
